name: CI

on:
  pull_request:
    branches: [main]

jobs:
  order-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: order-api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: python -m ruff check app tests
      - run: python -m pytest tests -v

  delivery-worker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: delivery-worker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: python -m ruff check worker tests
      - run: python -m pytest tests -v
